export const data = [
  {
    id: 1,
    type: "text",
    name: "firstName",
    label: "First Name *",
    placeholder: "Enter first name",
  },
  {
    id: 2,
    type: "text",
    name: "lastName",
    label: "Last Name *",
    placeholder: "Enter last name",
  },
  {
    id: 3,
    type: "text",
    name: "email",
    label: "Your Email *",
    placeholder: "Enter email",
  },
  {
    id: 4,
    type: "tel",
    name: "phoneNumber",
    label: "Phone Number*",
    placeholder: "Enter phone number",
  },
  {
    id: 5,
    type: "date",
    name: "date",
    label: "Date of Event *",
    //placeholder: 'Enter date ',
  },
  {
    id: 6,
    type: "number",
    name: "budget",
    label: "Event Budget *",
    placeholder: "Enter budget",
  },
  {
    id: 7,
    type: "text",
    name: "city",
    label: "City of Event *",
    placeholder: "Enter city of event",
  },
  {
    id: 8,
    type: "text",
    name: "country",
    label: "Country of event *",
    placeholder: "Enter country of event",
  },
];
